// Generated by https://quicktype.io

export interface AuthResponse {
	token: string;
	error?: string;
}

export interface UserResponse {
	user: User;
	error?: string;
}

export interface User {
	_id: string;
	username: string;
	email: string;
	image: string;
}

export interface DeleteResponse {
	msg: string;
	error?: string;
}

export interface GetResponse {
	lessons?: Lesson[];
	notes?: Note[];
	tasks?: Task[];
	error?: string;
}

export interface LessonsResponse {
	lessons: Lesson[];
	error?: string;
}

export interface LessonSaveResponse {
	lesson: Lesson;
	error?: string;
}

export interface NoteSaveResponse {
	note: Note;
	error?: string;
}

export interface Lesson {
	_id: string;
	lesson: string;
	nrc: number;
	teacher: string;
	schedlue: Schedlue[];
	createdAt: string;
	updatedAt: string;
}

export interface NoteResponse {
	note: Note;
}

export interface Note {
	title: string;
	body: string;
	images: Image[];
	_id: string;
	createdAt: string;
	updatedAt: string;
}

export interface Image {
	url: string;
}

export interface Schedlue {
	day: string;
	hours: string;
}

export interface SaveTaskResponse {
	task: Task;
	error?: string;
}

export interface Task {
	title: string;
	body: string;
	complete: boolean;
	images: Image[];
	dayLimit: string;
	_id: string;
	lesson: string;
	createdAt: string;
	updatedAt: string;
}
